/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_lpuart.h"
#include "fsl_clock.h"
#include "fsl_lpi2c.h"
#include "fsl_gpio.h"
#include "fsl_port.h"
#include "fsl_powerquad.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* BOARD_InitPeripherals defines for LP_FLEXCOMM3 */
/* Definition of peripheral ID */
#define LP_FLEXCOMM3_PERIPHERAL LPI2C3
/* Definition of peripheral base address */
#define LP_FLEXCOMM3_PERIPHERAL_BASE LPI2C3_BASE
/* Definition of the clock source frequency */
#define LP_FLEXCOMM3_CLOCK_SOURCE 12000000UL
/* Alias for GPIO5 peripheral */
#define GPIO5_GPIO GPIO5
/* Alias for PORT5 */
#define GPIO5_PORT PORT5
/* GPIO5 interrupt vector ID (number). */
#define GPIO5_INT_0_IRQN GPIO50_IRQn
/* GPIO5 interrupt vector priority. */
#define GPIO5_INT_0_IRQ_PRIORITY 3
/* GPIO5 interrupt handler identifier. */
#define GPIO5_INT_0_IRQHANDLER GPIO50_IRQHandler
/* Definition of peripheral ID */
#define POWERQUAD_PERIPHERAL POWERQUAD

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const lpi2c_master_config_t LP_FLEXCOMM3_masterConfig;
extern const pq_config_t POWERQUAD_config;

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
