/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v14.0
processor: MCXN947
package_id: MCXN947VDF
mcu_data: ksdk2_0
processor_version: 15.1.0
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: ef7ecff6-0855-450c-9af8-8018a5670f27
  called_from_default_init: true
  selectedCore: cm33_core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system_54b53072540eeeb8f8e9343e71f28176'
- global_system_definitions:
  - user_definitions: ''
  - user_includes: ''
  - global_init: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'uart_cmsis_common'
- type_id: 'uart_cmsis_common_9cb8e302497aa696fdbb5a4fd622c2a8'
- global_USART_CMSIS_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'gpio_adapter_common'
- type_id: 'gpio_adapter_common_57579b9ac814fe26bf95df0a384c36b6'
- global_gpio_adapter_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "peripherals.h"

/***********************************************************************************************************************
 * BOARD_InitPeripherals functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * NVIC initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'NVIC'
- type: 'nvic'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'nvic_57b5eef3774cc60acaede6f5b8bddc67'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'NVIC'
- config_sets:
  - nvic:
    - interrupt_table:
      - 0: []
      - 1: []
    - interrupts: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* Empty initialization function (commented out)
static void NVIC_init(void) {
} */

/***********************************************************************************************************************
 * LP_FLEXCOMM3 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LP_FLEXCOMM3'
- type: 'lpflexcomm_lpi2c'
- mode: 'polling'
- custom_name_enabled: 'false'
- type_id: 'lpflexcomm_lpi2c_3fbbc73b1f9664cf3a89fd1cb940c94e'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LP_FLEXCOMM3'
- config_sets:
  - generalCfg:
    - lpi2c_mode: 'master'
    - clock_configuration:
      - clockSource: 'LPFLEXCOMMFunctionClock'
      - clockSourceFreq: 'ClocksTool_DefaultInit'
    - master_config:
      - enableMaster: 'true'
      - enableDoze: 'true'
      - debugEnable: 'false'
      - ignoreAck: 'false'
      - pinConfig: 'kLPI2C_2PinOpenDrain'
      - baudRate_Hz: '400000'
      - realBaudRateCount: []
      - busIdleTimeout_ns: '0'
      - pinLowTimeout_ns: '0'
      - sdaGlitchFilterWidth_ns: '0'
      - sclGlitchFilterWidth_ns: '0'
      - hostRequest:
        - enable: 'false'
        - source: 'kLPI2C_HostRequestExternalPin'
        - polarity: 'kLPI2C_HostRequestPinActiveHigh'
      - enable_dma_master: 'false'
      - lpi2c_dma_master_struct_t:
        - DMATxEnable: 'true'
        - DMARxEnable: 'true'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpi2c_master_config_t LP_FLEXCOMM3_masterConfig = {
  .enableMaster = true,
  .enableDoze = true,
  .debugEnable = false,
  .ignoreAck = false,
  .pinConfig = kLPI2C_2PinOpenDrain,
  .baudRate_Hz = 400000UL,
  .busIdleTimeout_ns = 0UL,
  .pinLowTimeout_ns = 0UL,
  .sdaGlitchFilterWidth_ns = 0U,
  .sclGlitchFilterWidth_ns = 0U,
  .hostRequest = {
    .enable = false,
    .source = kLPI2C_HostRequestExternalPin,
    .polarity = kLPI2C_HostRequestPinActiveHigh
  }
};

static void LP_FLEXCOMM3_init(void) {
  /* LP_FLEXCOMM3 LPI2C master initialization */
  LPI2C_MasterInit(LP_FLEXCOMM3_PERIPHERAL, &LP_FLEXCOMM3_masterConfig, LP_FLEXCOMM3_CLOCK_SOURCE);
}

/***********************************************************************************************************************
 * GPIO5 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'GPIO5'
- type: 'gpio'
- mode: 'GPIO'
- custom_name_enabled: 'false'
- type_id: 'gpio_bdab6a68c04595b6073dff48897d210f'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'GPIO5'
- config_sets:
  - fsl_gpio:
    - enable_irq: 'true'
    - port_interrupt:
      - IRQn: 'GPIO50_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - enable_irq_1: 'false'
    - gpio_interrupt_1:
      - IRQn: 'GPIO01_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '1'
      - enable_custom_name: 'false'
    - enable_irq_EFT: 'false'
    - port_interrupt_EFT:
      - IRQn: 'PORT_EFT_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '2'
      - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

static void GPIO5_init(void) {
  /* Make sure, the clock gate for port 5 is enabled (e. g. in pin_mux.c) */
  /* Interrupt vector GPIO50_IRQn priority settings in the NVIC. */
  NVIC_SetPriority(GPIO5_INT_0_IRQN, GPIO5_INT_0_IRQ_PRIORITY);
  /* Enable interrupt GPIO50_IRQn request in the NVIC. */
  EnableIRQ(GPIO5_INT_0_IRQN);
}

/***********************************************************************************************************************
 * POWERQUAD initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'POWERQUAD'
- type: 'powerquad'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'powerquad_f33ee2e3c5b6760278a873999726fbe6'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'POWERQUAD'
- config_sets:
  - fsl_powerquad:
    - powerQuadConfig:
      - inputAFormat: 'kPQ_Float'
      - inputAPrescale: '0'
      - inputBFormat: 'kPQ_Float'
      - inputBPrescale: '0'
      - outputFormat: 'kPQ_Float'
      - outputPrescale: '0'
      - tmpFormat: 'kPQ_Float'
      - tmpPrescale: '0'
      - machineFormat: 'kPQ_Float'
      - tmpBaseValue: '0xE0000000UL'
    - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const pq_config_t POWERQUAD_config = {
  .inputAFormat = kPQ_Float,
  .inputAPrescale = 0,
  .inputBFormat = kPQ_Float,
  .inputBPrescale = 0,
  .outputFormat = kPQ_Float,
  .outputPrescale = 0,
  .tmpFormat = kPQ_Float,
  .tmpPrescale = 0,
  .machineFormat = kPQ_Float,
  .tmpBase = (uint32_t *)0xE0000000UL
};

static void POWERQUAD_init(void) {
  PQ_Init(POWERQUAD_PERIPHERAL);
  PQ_SetConfig(POWERQUAD_PERIPHERAL, &POWERQUAD_config);
}

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void)
{
  /* Initialize components */
  LP_FLEXCOMM3_init();
  GPIO5_init();
  POWERQUAD_init();
}

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void)
{
  BOARD_InitPeripherals();
}
